"""add_ps34_models_and_fields

Revision ID: 75879f7fbb4e
Revises: 007ebe81a18e
Create Date: 2026-09-07 11:20:46.328188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75879f7fbb4e'
down_revision: Union[str, Sequence[str], None] = '007ebe81a18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('citizen_upi_vpa', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('channel', sa.String(length=50), nullable=True))
    op.add_column('complaints', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('complaints', sa.Column('statement_of_fact', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('photo_urls', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_complaints_category'), 'complaints', ['category'], unique=False)
    op.create_index(op.f('ix_complaints_channel'), 'complaints', ['channel'], unique=False)
    op.add_column('inspection_products', sa.Column('photo_urls', sa.JSON(), nullable=True))
    op.add_column('notices', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('notices', sa.Column('controller_remarks', sa.Text(), nullable=True))
    op.add_column('notices', sa.Column('approved_by_officer_id', sa.String(length=36), nullable=True))
    op.add_column('notices', sa.Column('statutory_deadline', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_notices_status'), 'notices', ['status'], unique=False)
    op.create_foreign_key(None, 'notices', 'users', ['approved_by_officer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notices', type_='foreignkey')
    op.drop_index(op.f('ix_notices_status'), table_name='notices')
    op.drop_column('notices', 'statutory_deadline')
    op.drop_column('notices', 'approved_by_officer_id')
    op.drop_column('notices', 'controller_remarks')
    op.drop_column('notices', 'status')
    op.drop_column('inspection_products', 'photo_urls')
    op.drop_index(op.f('ix_complaints_channel'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category'), table_name='complaints')
    op.drop_column('complaints', 'photo_urls')
    op.drop_column('complaints', 'statement_of_fact')
    op.drop_column('complaints', 'category')
    op.drop_column('complaints', 'channel')
    op.drop_column('complaints', 'citizen_upi_vpa')
    # ### end Alembic commands ###
